### ISSUE TITLE
conda env for FAST

### ISSUE THREAD

**Issue by 0ut0fcontrol** [hnlab/FAST#1]
Conda env `fast` for this project.

@xuelianl 

2021/07/05 updated, 18b0e332b409f52671a4d0bb4fa6f1595739c2c4
```yml
# conda env create -f conda.env.fast.yml
name: fast
channels:
  - pytorch
  - rusty1s
  - conda-forge
dependencies:
  - python
  - jupyter
  - requests
  - setuptools
  # linter and formatter
  - pylint
  - black
  - isort
  # utility
  - tqdm
  # data analysis
  - h5py
  - numpy
  - scipy
  - pandas
  - scikit-learn
  # visualization
  - matplotlib
  - seaborn
  - plotly
  - nglview
  # cheminfo
  - openbabel
  - rdkit
  - biopython
  - chembl_webresource_client
  # molecular mechanics
  - openmm
  - ambertools
  - parmed
  - mdtraj
  - mdanalysis
  - openff-toolkit
  # machine learning
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pytorch-geometric
```
